### ISSUE TITLE
Fibonacci.cc bug in the initialization of the even_sum

### ISSUE THREAD

**Issue by dfourni2** [maxdschwarz/mschwa26PullRequests#10]
Steps to Reproduce

First step to reproduce the issue/bug
Run Program
Second step to reproduce the issue/bug
Notice the expected value
Third step to reproduce the issue/bug
notice that the expected value is less than the actual value by 1
Expected Behavior A clear and concise description of what you expected to happen.

Actual Behavior A clear and concise description of what actually happened.
One number greater than the expected value

Any other relevant information
Possible Solution If you have any suggestions for a possible solution, please include them here.
Change the initialization of the even_sum to zero instead of 1
Related Issues Are there any related issues? If so, please link to them here.

Priority How critical is this issue/bug? Low, medium, or high priority?
Low
Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
Always every time the program is run the sum will be 1 greater than what it is supposed to be
Impact What is the impact of this issue/bug? Low, medium, or high?
Medium since the code will be wrong every time it is run

**Comment by aknobel18** [comment]
changed the 1 in line 7 to 0 when initializing even_sum
