### ISSUE TITLE
Bug in line 4 of sum_even_fibonacci.py

### ISSUE THREAD

**Issue by aknobel18** [maxdschwarz/mschwa26PullRequests#11]
Description A clear and concise description of what the issue/bug is.
The code does not enter the while loop because of the logic in line 4. 

Steps to Reproduce
First step to reproduce the issue/bug
Run the program
Second step to reproduce the issue/bug
Look at the output of the sum 
Third step to reproduce the issue/bug
Notice that the code does not correctly sum the even fibonacci sequence because it does not enter the while loop

Expected Behavior A clear and concise description of what you expected to happen.
The program should enter the while loop and sum the even fibonacci numbers. 

Actual Behavior A clear and concise description of what actually happened.
The code does not enter the while loop and prints 1. 

Screenshots If applicable, add screenshots to help explain the issue/bug.

Additional Information

Operating System: MacOS
Browser: Google Chrome
Version: Monterey 12.6.3
Any other relevant information

Possible Solution If you have any suggestions for a possible solution, please include them here.
Change the > to <. 

Related Issues Are there any related issues? If so, please link to them here.
No

Priority How critical is this issue/bug? Low, medium, or high priority?
High

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
Always

Impact What is the impact of this issue/bug? Low, medium, or high?
High

**Comment by caseyforey** [comment]
Fixed this issue by swapping the greater than to a less than.
