### ISSUE TITLE
Bug in line 5 of sum_fibonacci.py 

### ISSUE THREAD

**Issue by aknobel18** [maxdschwarz/mschwa26PullRequests#6]
The logical operator == is written as = in line 5 which is giving a run time error. 

Run the file 

The value b%2 should be compared to 0 and return true or false in the if-statement. 

The program gives a RunTime error. 

Additional Information
Operating System: MacOS 
Browser: Google Chrome
Version: Monterey 12.6.3
Any other relevant information

Possible Solution If you have any suggestions for a possible solution, please include them here.
The = in line 5 should be changed to ==. 

Related Issues Are there any related issues? If so, please link to them here.
No

Priority How critical is this issue/bug? Low, medium, or high priority?
Low

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
Always

Impact What is the impact of this issue/bug? Low, medium, or high?
High

**Comment by caseyforey** [comment]
Added the correct logical operator to the file.
