### ISSUE TITLE
Issue with remove_duplicates.py

### ISSUE THREAD

**Issue by caseyforey** [maxdschwarz/mschwa26PullRequests#8]
Description: Line 11 does not return anything

Steps to reproduce:
1. Run the program
2. try to use the returned value
3. value will be null or nonexistent
Expected behavior: To return the vector without duplicates
Actual behavior: Does not return any vector

Operating System: Windows 11 
Browser: Firefox 
Version: 110.0.1

Solution: Add a return value to line 11
This is a critical issue with the code
Reproducible in every instance of the program
High impact for anyone using that function

**Comment by maxdschwarz** [comment]
Issue fixed
