### ISSUE TITLE
RGB Max Value in rgb_to_hex.py

### ISSUE THREAD

**Issue by maxdschwarz** [maxdschwarz/mschwa26PullRequests#9]
Expected Behavior: RGB max value should be 255. 
Actual Behavior: RGB max value is 254.
`def rgb_to_hex(r, g, b):
    r = max(0, min(254, r))
    g = max(0, min(254, g))
    b = max(0, min(254, b))
    return '{:02X}{:02X}{:02X}'.format(r, g, b)`
Operating System: Mac
Browser: Chrome
Version: 110.0
Possible solution: Change the RGB max value to 255. 
Priority: Medium. 
Reproducibility: always
Impact: Medium

**Comment by aknobel18** [comment]
changed RGB max value to 255
